// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: account.proto at 19:1
package com.tmauto.argus.mapi.model;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class TMProfile extends Message<TMProfile, TMProfile.Builder> {
  public static final ProtoAdapter<TMProfile> ADAPTER = new ProtoAdapter_TMProfile();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ID = 0;

  public static final String DEFAULT_PHONE = "";

  public static final String DEFAULT_USERNAME = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String phone;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String username;

  public TMProfile(Integer id, String phone, String username) {
    this(id, phone, username, ByteString.EMPTY);
  }

  public TMProfile(Integer id, String phone, String username, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.phone = phone;
    this.username = username;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.phone = phone;
    builder.username = username;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TMProfile)) return false;
    TMProfile o = (TMProfile) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(phone, o.phone)
        && Internal.equals(username, o.username);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (phone != null ? phone.hashCode() : 0);
      result = result * 37 + (username != null ? username.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (phone != null) builder.append(", phone=").append(phone);
    if (username != null) builder.append(", username=").append(username);
    return builder.replace(0, 2, "TMProfile{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TMProfile, Builder> {
    public Integer id;

    public String phone;

    public String username;

    public Builder() {
    }

    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    public Builder phone(String phone) {
      this.phone = phone;
      return this;
    }

    public Builder username(String username) {
      this.username = username;
      return this;
    }

    @Override
    public TMProfile build() {
      return new TMProfile(id, phone, username, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TMProfile extends ProtoAdapter<TMProfile> {
    ProtoAdapter_TMProfile() {
      super(FieldEncoding.LENGTH_DELIMITED, TMProfile.class);
    }

    @Override
    public int encodedSize(TMProfile value) {
      return (value.id != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.id) : 0)
          + (value.phone != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.phone) : 0)
          + (value.username != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.username) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, TMProfile value) throws IOException {
      if (value.id != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.id);
      if (value.phone != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.phone);
      if (value.username != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.username);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TMProfile decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.phone(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.username(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public TMProfile redact(TMProfile value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
